server:
  port: 4001
  host: 127.0.0.1
  tomcat:
    uri-encoding: UTF-8
    max-threads: 400
    acceptCount: 200
    max-connections: 10000
    connection-timeout: 15000

spring:
  application:
    name: dubbo-example
    version: 0.1.0
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

dubbo:
  application:
    name: dubbo-example
    # 解决启动报错(java.util.NoSuchElementException: No value present)的问题，待后续dubbo 更新后，不用再进行配置 https://github.com/apache/dubbo/issues/10795
    metadata-service-protocol: tri
  registry:
    id: nacos-rg
    address: nacos://localhost:8848?username=nacos&password=nacos
  config-center:
    address: nacos://localhost:8848?username=nacos&password=nacos
  metadata-report:
    address: nacos://localhost:8848?username=nacos&password=nacos
  protocol:
    name: tri
    port: 40001
  provider:
    token: false

logging:
  level:
    org.apache.dubbo: debug
